apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-fluent-bit
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-fluent-bit
    meta.crossplane.io/description: Installs the Fluent Bit log processor Helm chart.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.0.2"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
